on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ release-please.steps.release.outputs.release_created }}
    steps:
      - name: echo
        run: echo 'steps run'

      # - uses: actions/checkout@v3
      #   if: ${{ steps.release.outputs.release_created }}
      # - uses: pnpm/action-setup@v2
      #   with:
      #     version: 8
      #   if: ${{ steps.release.outputs.release_created }}
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version-file: '.nvmrc'
      #     cache: 'pnpm'
      #   if: ${{ steps.release.outputs.release_created }}

      # - name: install
      #   run: pnpm i
      #   if: ${{ steps.release.outputs.release_created }}

      # - name: install vsce
      #   run: pnpm add -g @vscode/vsce
      #   if: ${{ steps.release.outputs.release_created }}

      # - name: publish
      #   run: |
      #     pnpm run vsce:package
      #     pnpm run vsce:publish
      #   if: ${{ steps.release.outputs.release_created }}
